# Generated by Django 3.1.6 on 2021-02-07 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField(max_length=9)),
                ('student_email', models.CharField(max_length=100)),
                ('student_first_name', models.CharField(max_length=25)),
                ('student_last_name', models.CharField(max_length=50)),
            ],
        ),
    ]
