# Generated by Django 3.1.6 on 2021-04-01 22:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_credits', models.IntegerField()),
                ('course_name', models.CharField(max_length=50)),
                ('course_code', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_name', models.CharField(max_length=100)),
                ('program_course_total', models.IntegerField()),
                ('program_credits', models.IntegerField()),
                ('program_department', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Program_Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.IntegerField()),
                ('program', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_campus', models.CharField(default='Mayaguez', max_length=20)),
                ('student_program', models.CharField(default='ICOM', max_length=20)),
                ('student_gpa', models.CharField(default=0.0, max_length=4)),
                ('student_major_gpa', models.CharField(default=0.0, max_length=4)),
                ('student_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentCourses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_grade', models.CharField(max_length=1)),
                ('course_professor', models.CharField(max_length=50)),
                ('course_is_concentration', models.BooleanField()),
                ('course_time_start', models.TimeField()),
                ('course_time_end', models.TimeField()),
                ('course_section', models.CharField(max_length=10)),
                ('course_semester', models.IntegerField()),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='UPR_Grader.courses')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='UPR_Grader.students')),
            ],
        ),
        migrations.CreateModel(
            name='Enrolled_Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=9)),
                ('course_title', models.CharField(max_length=100)),
                ('course_credits', models.CharField(max_length=2)),
                ('student', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='UPR_Grader.students')),
            ],
        ),
    ]
