# Generated by Django 3.1.6 on 2021-04-01 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UPR_Grader', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='course_code',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='program_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='program_courses',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UPR_Grader.courses', to_field='course_code'),
        ),
        migrations.AlterField(
            model_name='program_courses',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UPR_Grader.program', to_field='program_name'),
        ),
    ]
