# Generated by Django 3.1.6 on 2021-02-09 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UPR_Grader', '0002_auto_20210207_1537'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='student_id',
        ),
    ]
