# Generated by Django 3.1.6 on 2021-04-02 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UPR_Grader', '0002_auto_20210401_1834'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentcourses',
            name='course_semester',
        ),
        migrations.RemoveField(
            model_name='studentcourses',
            name='course_time_end',
        ),
        migrations.RemoveField(
            model_name='studentcourses',
            name='course_time_start',
        ),
        migrations.AlterField(
            model_name='studentcourses',
            name='course_is_concentration',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='studentcourses',
            name='course_professor',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='studentcourses',
            name='course_section',
            field=models.CharField(default='005', max_length=10),
        ),
    ]
