# Generated by Django 3.1.6 on 2021-02-12 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UPR_Grader', '0003_remove_students_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='student_password',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='students',
            name='student_email',
            field=models.EmailField(max_length=100),
        ),
    ]
