# Generated by Django 3.1.6 on 2021-02-12 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UPR_Grader', '0004_auto_20210212_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='student_password',
            field=models.CharField(max_length=500),
        ),
    ]
