# Generated by Django 3.1.6 on 2021-04-02 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UPR_Grader', '0005_auto_20210402_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentcourses',
            name='course_professor',
            field=models.CharField(default='', max_length=50),
        ),
    ]
