# Generated by Django 3.1.6 on 2021-02-17 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UPR_Grader', '0006_auto_20210217_1640'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='students',
            options={},
        ),
        migrations.AlterModelManagers(
            name='students',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='students',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='students',
            name='email',
        ),
        migrations.RemoveField(
            model_name='students',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='students',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='students',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='students',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='students',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='students',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='students',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='students',
            name='password',
        ),
        migrations.RemoveField(
            model_name='students',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='students',
            name='username',
        ),
    ]
