# Generated by Django 3.1.6 on 2021-04-02 18:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('UPR_Grader', '0006_auto_20210402_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentcourses',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
