# Generated by Django 3.1.6 on 2021-02-17 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UPR_Grader', '0007_auto_20210217_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='last_login',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
