# Generated by Django 3.1.7 on 2021-03-05 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UPR_Grader', '0008_students_last_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrolled_Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=9)),
                ('course_title', models.CharField(max_length=100)),
                ('course_credits', models.CharField(max_length=2)),
            ],
        ),
    ]
