# Generated by Django 3.1.6 on 2021-04-02 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UPR_Grader', '0009_auto_20210402_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentcourses',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UPR_Grader.courses'),
        ),
    ]
