# Generated by Django 3.1.6 on 2021-03-02 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UPR_Grader', '0009_auto_20210302_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='student_campus',
            field=models.CharField(default='None', max_length=20),
        ),
        migrations.AlterField(
            model_name='students',
            name='student_program',
            field=models.CharField(default='None', max_length=20),
        ),
    ]
