# Generated by Django 3.1.6 on 2021-04-02 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UPR_Grader', '0010_auto_20210402_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentcourses',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UPR_Grader.courses', to_field='course_code'),
        ),
    ]
