# Generated by Django 3.1.6 on 2021-04-02 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UPR_Grader', '0011_auto_20210402_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentcourses',
            name='course_grade',
            field=models.CharField(default='-', max_length=1),
        ),
    ]
