# Generated by Django 3.1.6 on 2021-04-05 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UPR_Grader', '0013_auto_20210403_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='student_total_credit_hours_attempted',
            field=models.CharField(default=0, max_length=1000),
        ),
        migrations.AddField(
            model_name='students',
            name='student_total_grade_points',
            field=models.CharField(default=0, max_length=1000),
        ),
    ]
