# Generated by Django 3.1.6 on 2021-04-05 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UPR_Grader', '0017_auto_20210405_1602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='student_total_credit_hours_attempted',
        ),
        migrations.RemoveField(
            model_name='students',
            name='student_total_grade_points',
        ),
    ]
